version: 2.1
jobs:
  push-image:
    docker:
      - image: docker:dind
        environment:
          ACCOUNT: "306811362825"
          REGION: "us-gov-west-1"
    steps:
      - checkout
      - run:
          name: "Log in to prod aws ecr"
          command: |
            # install dependencies
            apk add py3-pip
            pip3 install awscli

            # configure aws credentials file
            mkdir -p ~/.aws/
            touch ~/.aws/credentials
            echo '
            [default]
            aws_access_key_id=${AWS_ACCESS_KEY_ID}
            aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
            ' >> ~/.aws/credentials

            # configure aws config file
            mkdir -p ~/.aws/
            touch ~/.aws/config
            echo '
            [default]
            region=us-gov-west-1
            ' >> ~/.aws/config

            # log in to prod aws ecr
            aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Docker pull, build, tag, push"
          command: |
            # install dependencies
            apk update && apk add bash

            # run docker.sh
            ./docker.sh
  apply-terragrunt:
    docker:
      - image: alpine:3.16
    steps:
      - checkout
      - run:
          name: Get git
          command: |
            # get current git commit
            echo $CIRCLE_SHA1
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            echo $SHORT_GIT_HASH

            # show all files changed with this current git commit
            git diff-tree --no-commit-id --name-only -r $SHORT_GIT_HASH
workflows:
  docker:
    jobs:
      # - push-image
      - apply-terragrunt
          filters
            branches:
              only: circleci
