version: 2.1
jobs:
  push-image:
    docker:
      - image: docker:dind
        environment:
          ACCOUNT: "306811362825"
          REGION: "us-gov-west-1"
    steps:
      - checkout
      - run:
          name: "Log in to prod aws ecr"
          command: |
            # install dependencies
            apk add py3-pip
            pip3 install awscli

            # configure aws credentials file
            mkdir -p ~/.aws/
            touch ~/.aws/credentials
            echo '
            [default]
            aws_access_key_id=${AWS_ACCESS_KEY_ID}
            aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
            ' >> ~/.aws/credentials

            # configure aws config file
            mkdir -p ~/.aws/
            touch ~/.aws/config
            echo '
            [default]
            region=us-gov-west-1
            ' >> ~/.aws/config

            # log in to prod aws ecr
            aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: "Docker pull, build, tag, push"
          command: |
            # install dependencies
            apk update && apk add bash

            # run docker.sh
            ./docker.sh
  terragrunt-plan:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |

            # install dependencies
            apt update && apt install -y git wget

            # install terraform
            wget -O terraform.zip https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip && unzip terraform.zip && rm terraform.zip && mv terraform /usr/bin/terraform && chmod uo+x /usr/bin/terraform

            # install terragrunt
            wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.35.8/terragrunt_linux_amd64 && mv terragrunt_linux_amd64 /usr/bin/terragrunt && chmod uo+x /usr/bin/terragrunt
      - run:
          name: Run terragrunt plan
          command: |

            # get current git commit
            SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)

            # show all files changed with this current git commit
            CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r $SHORT_GIT_HASH)

            echo $CHANGED_FILES

            DEPLOYMENT_FILES=(
              env/dev/hub/formio/tenants/epa/service/terragrunt.hcl
              env/dev/hub/formio/tenants/irs/service/terragrunt.hcl
              env/dev/hub/formio/tenants/portal/service/terragrunt.hcl
              env/dev/hub/formio/pdf-server/service/terragrunt.hcl
            )

            echo $DEPLOYMENT_FILES

            # # for each changed file in this current commit
            # for CHANGED_FILE in $CHANGED_FILES; do
            #
            #   # if any our deployment files were commited, change to that directory and run terragrunt plan
            #   if [[ " ${DEPLOYMENT_FILES[*]} " =~ " ${CHANGED_FILE} " ]]; then
            #
            #     # # get directory of changed file
            #     # DIRECTORY=$(dirname "${CHANGED_FILE}")
            #     #
            #     # # change into that directory
            #     # cd $DIRECTORY
            #     #
            #     # # run terragrunt plan
            #     # terragrunt plan
            #   else
            #     echo "not in if statement"
            #   fi
            # done
workflows:
  docker:
    jobs:
      # - push-image
      - terragrunt-plan:
          filters:
            branches:
              only: circleci
