## IRS Demo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: formservice
  template:
    metadata:
      labels:
        name: formservice
    spec:
      containers:
        - name: app
          image: 306881650362.dkr.ecr.us-gov-west-1.amazonaws.com/faas-sandb/microservice:8
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: HOST
              value: agency01-ms-sandb-02.appsquared.io
            - name: PORT
              value: '443'
            - name: ENTITYID
              value: urn:gov:gsa:SAML:2.0.profiles:sp:sso:irs.gov:irs-form